[package]
name = "rust-pseudokude"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
winapi = { version = "0.3", features = ["consoleapi", "fileapi", "handleapi", "minwindef", "processenv", "winbase", "wincon", "winnt"] }
